const catList = [
  {
    id: 1,
    years: "2y",
    name: "搗灰",
    png: "./images/jodicat.png",
    hashtag1: "慢熱",
    hashtag2: "獨立",
    hashtag3: "有經驗佳",
    quotes: ["我是你最好的室友", "我靜靜的看著你", "你是我一輩子的依靠嗎?"],
  },
  {
    id: 2,
    years: "8m",
    name: "芝麻",
    png: "./images/phonecat1.jpg",
    hashtag1: "黏人",
    hashtag2: "話多",
    hashtag3: "新手友善",
    quotes: ["我想吃肉泥", "奴才去哪?", "奴才到哪都要跟著"],
  },
  {
    id: 3,
    years: "1y",
    name: "鴨蛋",
    png: "./images/phonecat2.jpg",
    hashtag1: "穩定",
    hashtag2: "安靜",
    hashtag3: "多貓",
    quotes: ["我會一直守護著主子", "我在冥想", "安靜點"],
  },
  {
    id: 4,
    years: "4y",
    name: "豆漿",
    png: "./images/phonecat3.jpg",
    hashtag1: "黏人",
    hashtag2: "話多",
    hashtag3: "單貓",
    quotes: ["你只能有我一個!", "我在跟你講話唷~", "好想霸佔主子的愛"],
  },
  {
    id: 5,
    years: "4y",
    name: "豆漿",
    png: "./images/phonecat4.jpg",
    hashtag1: "黏人",
    hashtag2: "話多",
    hashtag3: "單貓",
    quotes: ["你只能有我一個!", "我在跟你講話唷~", "好想霸佔主子的愛"],
  },
  {
    id: 6,
    years: "4y",
    name: "豆漿",
    png: "./images/phonecat5.jpg",
    hashtag1: "黏人",
    hashtag2: "話多",
    hashtag3: "單貓",
    quotes: ["你只能有我一個!", "我在跟你講話唷~", "好想霸佔主子的愛"],
  },
];

export default catList;
