const catList = [
  {
    id: 1,
    years: "2y",
    name: "搗灰",
    sex: "弟弟",
    old: "1~3歲",
    color: "白",
    png: "./images/jodicat.png",
    hashtag: ["慢熱", "獨立", "穩定"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["我是你最好的室友", "我靜靜的看著你", "你是我一輩子的依靠嗎?"],
  },
  {
    id: 2,
    years: "8m",
    name: "芝麻",
    sex: "妹妹",
    color: "橘",
    old: "0~1歲",
    png: "./images/phonecat1.jpg",
    hashtag: ["黏人", "獨立", "話多"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["我想吃肉泥", "奴才去哪?", "奴才到哪都要跟著"],
  },
  {
    id: 3,
    years: "1y",
    name: "鴨蛋",
    sex: "弟弟",
    color: "虎斑",
    old: "0~1歲",
    png: "./images/phonecat2.jpg",
    hashtag: ["慢熱", "獨立", "穩定"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["我會一直守護著主子", "我在冥想", "安靜點"],
  },
  {
    id: 4,
    years: "4y",
    name: "豆漿",
    sex: "妹妹",
    color: "黑",
    old: "1~3歲",
    png: "./images/phonecat3.jpg",
    hashtag: ["黏人", "獨立", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["你只能有我一個!", "我在跟你講話唷~", "好想霸佔主子的愛"],
  },
  {
    id: 5,
    years: "4y",
    name: "豆漿",
    sex: "妹妹",
    color: "黑",
    old: "3~5歲",
    png: "./images/phonecat4.jpg",
    hashtag: ["慢熱", "獨立", "穩定"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["你只能有我一個!", "我在跟你講話唷~", "好想霸佔主子的愛"],
  },
  {
    id: 6,
    years: "4y",
    name: "豆漿",
    sex: "妹妹",
    color: "橘",
    old: "5歲以上",
    png: "./images/phonecat5.jpg",
    hashtag: ["黏人", "獨立", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["你只能有我一個!", "我在跟你講話唷~", "好想霸佔主子的愛"],
  },
];

export default catList;
