// 一次性腳本：再多寫入 50 筆隨機產生的貓咪測試資料（id 7~56）到 Firestore 的 "cats" collection。
// 用法： node scripts/seedMoreCats.mjs
//
// 資料格式與 src/components/card/catList.js 一致：
// { id, years, name, sex, old, color, png, hashtag, CatFriendly, needExperienced, quotes }
// - years 與 old 區間互相對應（例如 "8m" -> "0~1歲"、"4y" -> "3~5歲"）
// - hashtag 只使用篩選器的六種個性：穩定 / 慢熱 / 黏人 / 獨立 / 話多 / 撒嬌
// - png 使用 public/images 內既有的貓咪照片
//
// 與 seedCats.mjs 相同，使用專案既有的 firebase client 設定，不需要 service account key。
// 若 Firestore 規則不允許未登入寫入，請先到 Firebase Console -> Firestore -> 規則暫時開放，
// 寫完後記得改回安全的規則。重複執行是安全的（setDoc 會直接覆蓋同 id 的文件）。

import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyDf28BJbpv9PIgQcjzcy00bJH2n8u__lGk",
  authDomain: "adopt-cat-82b81.firebaseapp.com",
  projectId: "adopt-cat-82b81",
  storageBucket: "adopt-cat-82b81.firebasestorage.app",
  messagingSenderId: "753136638366",
  appId: "1:753136638366:web:a0ef906a4393acfb0f1e8f",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const moreCats = [
  {
    id: 7,
    years: "7y",
    name: "麻糬",
    sex: "弟弟",
    old: "5歲以上",
    color: "白",
    png: "./images/jodicat.jpg",
    hashtag: ["撒嬌", "話多", "黏人"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["我可以叫一整天唷", "早安，該起床餵我了", "我保證乖乖(大概)"],
  },
  {
    id: 8,
    years: "2m",
    name: "奶茶",
    sex: "妹妹",
    old: "0~1歲",
    color: "橘",
    png: "./images/jodicat2.jpg",
    hashtag: ["黏人", "撒嬌", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["抱我，現在，立刻", "大腿借我坐一下", "你看起來就很好躺"],
  },
  {
    id: 9,
    years: "4y",
    name: "布丁",
    sex: "弟弟",
    old: "3~5歲",
    color: "橘",
    png: "./images/jodicat3.jpg",
    hashtag: ["黏人", "話多"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["你去哪我就去哪", "你只能有我一個!", "紙箱是我的城堡"],
  },
  {
    id: 10,
    years: "7m",
    name: "可樂",
    sex: "妹妹",
    old: "0~1歲",
    color: "黑",
    png: "./images/jodicat4.jpg",
    hashtag: ["話多", "黏人"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["早安，該起床餵我了", "我想吃肉泥", "陽台的麻雀是我的電視"],
  },
  {
    id: 11,
    years: "2y",
    name: "拿鐵",
    sex: "妹妹",
    old: "1~3歲",
    color: "虎斑",
    png: "./images/phonecat1.jpg",
    hashtag: ["慢熱", "話多", "穩定"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["我不吵不鬧，只想靜靜陪著你", "我在跟你講話唷~", "你看起來就很好躺"],
  },
  {
    id: 12,
    years: "12y",
    name: "芋圓",
    sex: "弟弟",
    old: "5歲以上",
    color: "橘",
    png: "./images/phonecat2.jpg",
    hashtag: ["穩定", "慢熱", "獨立"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["你忙你的，我看著就好", "我不吵不鬧，只想靜靜陪著你", "我還在學習怎麼撒嬌"],
  },
  {
    id: 13,
    years: "9m",
    name: "仙草",
    sex: "妹妹",
    old: "0~1歲",
    color: "黑",
    png: "./images/phonecat3.jpg",
    hashtag: ["慢熱", "撒嬌", "獨立"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["書架第二層是我的觀察站", "奴才去哪?", "我在等一個家"],
  },
  {
    id: 14,
    years: "1y",
    name: "珍珠",
    sex: "弟弟",
    old: "1~3歲",
    color: "白",
    png: "./images/phonecat4.jpg",
    hashtag: ["穩定", "黏人", "獨立"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["你忙你的，我看著就好", "看著我的眼睛說你愛我", "我在等一個家"],
  },
  {
    id: 15,
    years: "2y",
    name: "湯圓",
    sex: "弟弟",
    old: "1~3歲",
    color: "白",
    png: "./images/phonecat5.jpg",
    hashtag: ["黏人", "話多", "撒嬌"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["早安，該起床餵我了", "看著我的眼睛說你愛我", "遇見你之後，流浪就結束了"],
  },
  {
    id: 16,
    years: "1y",
    name: "饅頭",
    sex: "妹妹",
    old: "1~3歲",
    color: "白",
    png: "./images/jodicat.jpg",
    hashtag: ["話多", "黏人", "撒嬌"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["奴才去哪?", "呼嚕嚕是我的告白", "我在等一個家"],
  },
  {
    id: 17,
    years: "4y",
    name: "花捲",
    sex: "妹妹",
    old: "3~5歲",
    color: "虎斑",
    png: "./images/jodicat2.jpg",
    hashtag: ["撒嬌", "黏人", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["看著我的眼睛說你愛我", "奴才去哪?", "每天都想聽你叫我的名字"],
  },
  {
    id: 18,
    years: "4y",
    name: "貢丸",
    sex: "妹妹",
    old: "3~5歲",
    color: "黑",
    png: "./images/jodicat3.jpg",
    hashtag: ["慢熱", "獨立"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["慢慢來，我們有一輩子", "熟了之後我會偷偷蹭你", "帶我回家好不好?"],
  },
  {
    id: 19,
    years: "2y",
    name: "蛋餅",
    sex: "妹妹",
    old: "1~3歲",
    color: "虎斑",
    png: "./images/jodicat4.jpg",
    hashtag: ["獨立", "慢熱"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["我只是慢熟，不是不愛你", "慢慢來，我們有一輩子", "我保證乖乖(大概)"],
  },
  {
    id: 20,
    years: "3y",
    name: "豆花",
    sex: "弟弟",
    old: "3~5歲",
    color: "白",
    png: "./images/phonecat1.jpg",
    hashtag: ["慢熱", "話多"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["我在冥想，勿擾", "看著我的眼睛說你愛我", "我在等一個家"],
  },
  {
    id: 21,
    years: "11y",
    name: "紅豆",
    sex: "弟弟",
    old: "5歲以上",
    color: "虎斑",
    png: "./images/phonecat2.jpg",
    hashtag: ["慢熱", "話多", "黏人"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["先讓我觀察你三天", "我可以叫一整天唷", "聽說你家沙發不錯?"],
  },
  {
    id: 22,
    years: "1y",
    name: "花生",
    sex: "妹妹",
    old: "1~3歲",
    color: "虎斑",
    png: "./images/phonecat3.jpg",
    hashtag: ["慢熱", "話多", "獨立"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["尾巴輕輕搖是我在說嗨", "你只能有我一個!", "遇見你之後，流浪就結束了"],
  },
  {
    id: 23,
    years: "2m",
    name: "玉米",
    sex: "弟弟",
    old: "0~1歲",
    color: "橘",
    png: "./images/phonecat4.jpg",
    hashtag: ["穩定", "慢熱", "獨立"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["太陽曬到哪，我就睡到哪", "我會在你回家時假裝不在意", "罐罐是我的靈魂糧食"],
  },
  {
    id: 24,
    years: "8y",
    name: "地瓜",
    sex: "妹妹",
    old: "5歲以上",
    color: "橘",
    png: "./images/phonecat5.jpg",
    hashtag: ["獨立", "穩定", "慢熱"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我口是心非，其實很想被摸", "我會在你回家時假裝不在意", "我保證乖乖(大概)"],
  },
  {
    id: 25,
    years: "6m",
    name: "南瓜",
    sex: "弟弟",
    old: "0~1歲",
    color: "橘",
    png: "./images/jodicat.jpg",
    hashtag: ["獨立", "黏人", "撒嬌"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["你忙你的，我看著就好", "你回家的腳步聲我都認得", "聽說你家沙發不錯?"],
  },
  {
    id: 26,
    years: "1y",
    name: "海苔",
    sex: "妹妹",
    old: "1~3歲",
    color: "黑",
    png: "./images/jodicat2.jpg",
    hashtag: ["慢熱", "穩定", "獨立"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["我只是慢熟，不是不愛你", "慢慢來，我們有一輩子", "我的夢想是有一個窗邊座位"],
  },
  {
    id: 27,
    years: "4y",
    name: "起司",
    sex: "弟弟",
    old: "3~5歲",
    color: "虎斑",
    png: "./images/jodicat3.jpg",
    hashtag: ["黏人", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["門關起來我會唱歌給你聽", "看著我的眼睛說你愛我", "聽說你家沙發不錯?"],
  },
  {
    id: 28,
    years: "4m",
    name: "奶酪",
    sex: "妹妹",
    old: "0~1歲",
    color: "白",
    png: "./images/jodicat4.jpg",
    hashtag: ["撒嬌", "黏人"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["奴才去哪?", "蹭蹭是我的打招呼方式", "我還在學習怎麼撒嬌"],
  },
  {
    id: 29,
    years: "1y",
    name: "鬆餅",
    sex: "弟弟",
    old: "1~3歲",
    color: "虎斑",
    png: "./images/phonecat1.jpg",
    hashtag: ["慢熱", "話多", "撒嬌"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["尾巴輕輕搖是我在說嗨", "抱我，現在，立刻", "帶我回家好不好?"],
  },
  {
    id: 30,
    years: "3y",
    name: "甜甜圈",
    sex: "妹妹",
    old: "3~5歲",
    color: "黑",
    png: "./images/phonecat2.jpg",
    hashtag: ["穩定", "撒嬌", "獨立"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["我會在你回家時假裝不在意", "喵喵喵~聽我說話啦", "陽台的麻雀是我的電視"],
  },
  {
    id: 31,
    years: "4m",
    name: "泡芙",
    sex: "妹妹",
    old: "0~1歲",
    color: "黑",
    png: "./images/phonecat3.jpg",
    hashtag: ["穩定", "獨立", "慢熱"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["我只是慢熟，不是不愛你", "你忙你的，我看著就好", "我在等一個家"],
  },
  {
    id: 32,
    years: "3y",
    name: "果凍",
    sex: "妹妹",
    old: "3~5歲",
    color: "橘",
    png: "./images/phonecat4.jpg",
    hashtag: ["話多", "撒嬌"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["喵喵喵~聽我說話啦", "抱我，現在，立刻", "罐罐是我的靈魂糧食"],
  },
  {
    id: 33,
    years: "9y",
    name: "布朗尼",
    sex: "弟弟",
    old: "5歲以上",
    color: "黑",
    png: "./images/phonecat5.jpg",
    hashtag: ["黏人", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["門關起來我會唱歌給你聽", "早安，該起床餵我了", "逗貓棒一揮，我就是獵人"],
  },
  {
    id: 34,
    years: "1y",
    name: "可頌",
    sex: "妹妹",
    old: "1~3歲",
    color: "橘",
    png: "./images/jodicat.jpg",
    hashtag: ["撒嬌", "黏人"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我想吃肉泥", "你只能有我一個!", "帶我回家好不好?"],
  },
  {
    id: 35,
    years: "4m",
    name: "貝果",
    sex: "妹妹",
    old: "0~1歲",
    color: "虎斑",
    png: "./images/jodicat2.jpg",
    hashtag: ["獨立", "慢熱", "穩定"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["安靜的午後最適合打盹", "慢慢來，我們有一輩子", "聽說你家沙發不錯?"],
  },
  {
    id: 36,
    years: "5m",
    name: "吐司",
    sex: "妹妹",
    old: "0~1歲",
    color: "白",
    png: "./images/jodicat3.jpg",
    hashtag: ["獨立", "慢熱", "穩定"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["慢慢來，我們有一輩子", "熟了之後我會偷偷蹭你", "逗貓棒一揮，我就是獵人"],
  },
  {
    id: 37,
    years: "7y",
    name: "蜂蜜",
    sex: "弟弟",
    old: "5歲以上",
    color: "橘",
    png: "./images/jodicat4.jpg",
    hashtag: ["話多", "黏人", "撒嬌"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["鍵盤很好躺，我幫你上班", "你回家的腳步聲我都認得", "我在等一個家"],
  },
  {
    id: 38,
    years: "1y",
    name: "抹茶",
    sex: "弟弟",
    old: "1~3歲",
    color: "黑",
    png: "./images/phonecat1.jpg",
    hashtag: ["穩定", "撒嬌"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我會在你回家時假裝不在意", "喵喵喵~聽我說話啦", "逗貓棒一揮，我就是獵人"],
  },
  {
    id: 39,
    years: "5y",
    name: "烏龍",
    sex: "妹妹",
    old: "5歲以上",
    color: "黑",
    png: "./images/phonecat2.jpg",
    hashtag: ["話多", "撒嬌", "黏人"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["我想吃肉泥", "呼嚕嚕是我的告白", "我還在學習怎麼撒嬌"],
  },
  {
    id: 40,
    years: "5y",
    name: "鐵觀音",
    sex: "妹妹",
    old: "5歲以上",
    color: "黑",
    png: "./images/phonecat3.jpg",
    hashtag: ["穩定", "獨立"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["我不吵不鬧，只想靜靜陪著你", "我口是心非，其實很想被摸", "聽說你家沙發不錯?"],
  },
  {
    id: 41,
    years: "2y",
    name: "椪柑",
    sex: "妹妹",
    old: "1~3歲",
    color: "橘",
    png: "./images/phonecat4.jpg",
    hashtag: ["慢熱", "撒嬌", "穩定"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我會在你回家時假裝不在意", "早安，該起床餵我了", "陽台的麻雀是我的電視"],
  },
  {
    id: 42,
    years: "12y",
    name: "柚子",
    sex: "妹妹",
    old: "5歲以上",
    color: "橘",
    png: "./images/phonecat5.jpg",
    hashtag: ["話多", "撒嬌", "黏人"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我想吃肉泥", "今天也要一起睡唷", "陽台的麻雀是我的電視"],
  },
  {
    id: 43,
    years: "4y",
    name: "芭樂",
    sex: "弟弟",
    old: "3~5歲",
    color: "白",
    png: "./images/jodicat.jpg",
    hashtag: ["撒嬌", "黏人", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["蹭蹭是我的打招呼方式", "奴才去哪?", "罐罐是我的靈魂糧食"],
  },
  {
    id: 44,
    years: "11y",
    name: "蓮霧",
    sex: "妹妹",
    old: "5歲以上",
    color: "虎斑",
    png: "./images/jodicat2.jpg",
    hashtag: ["穩定", "獨立", "慢熱"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["太陽曬到哪，我就睡到哪", "安靜的午後最適合打盹", "聽說你家沙發不錯?"],
  },
  {
    id: 45,
    years: "1y",
    name: "龍眼",
    sex: "弟弟",
    old: "1~3歲",
    color: "黑",
    png: "./images/jodicat3.jpg",
    hashtag: ["慢熱", "話多"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我會在你回家時假裝不在意", "我想吃肉泥", "遇見你之後，流浪就結束了"],
  },
  {
    id: 46,
    years: "5m",
    name: "荔枝",
    sex: "弟弟",
    old: "0~1歲",
    color: "白",
    png: "./images/jodicat4.jpg",
    hashtag: ["穩定", "獨立", "慢熱"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["先讓我觀察你三天", "我喜歡在窗邊看鳥", "我保證乖乖(大概)"],
  },
  {
    id: 47,
    years: "5m",
    name: "木瓜",
    sex: "弟弟",
    old: "0~1歲",
    color: "白",
    png: "./images/phonecat1.jpg",
    hashtag: ["穩定", "獨立"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["慢慢來，我們有一輩子", "我在冥想，勿擾", "聽說你家沙發不錯?"],
  },
  {
    id: 48,
    years: "2y",
    name: "酪梨",
    sex: "弟弟",
    old: "1~3歲",
    color: "黑",
    png: "./images/phonecat2.jpg",
    hashtag: ["獨立", "撒嬌"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["尾巴輕輕搖是我在說嗨", "摸我摸我快摸我", "我的夢想是有一個窗邊座位"],
  },
  {
    id: 49,
    years: "7m",
    name: "毛豆",
    sex: "弟弟",
    old: "0~1歲",
    color: "黑",
    png: "./images/phonecat3.jpg",
    hashtag: ["話多", "黏人", "撒嬌"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["喵喵喵~聽我說話啦", "我可以叫一整天唷", "我在等一個家"],
  },
  {
    id: 50,
    years: "11m",
    name: "皮蛋",
    sex: "妹妹",
    old: "0~1歲",
    color: "黑",
    png: "./images/phonecat4.jpg",
    hashtag: ["話多", "黏人", "撒嬌"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["早安，該起床餵我了", "今天也要一起睡唷", "我保證乖乖(大概)"],
  },
  {
    id: 51,
    years: "1y",
    name: "油條",
    sex: "弟弟",
    old: "1~3歲",
    color: "虎斑",
    png: "./images/phonecat5.jpg",
    hashtag: ["撒嬌", "話多", "黏人"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["看著我的眼睛說你愛我", "今天也要一起睡唷", "帶我回家好不好?"],
  },
  {
    id: 52,
    years: "1y",
    name: "燒餅",
    sex: "妹妹",
    old: "1~3歲",
    color: "虎斑",
    png: "./images/jodicat.jpg",
    hashtag: ["撒嬌", "黏人"],
    CatFriendly: true,
    needExperienced: false,
    quotes: ["你回家的腳步聲我都認得", "奴才去哪?", "逗貓棒一揮，我就是獵人"],
  },
  {
    id: 53,
    years: "9m",
    name: "米糕",
    sex: "弟弟",
    old: "0~1歲",
    color: "白",
    png: "./images/jodicat2.jpg",
    hashtag: ["撒嬌", "黏人"],
    CatFriendly: true,
    needExperienced: true,
    quotes: ["門關起來我會唱歌給你聽", "呼嚕嚕是我的告白", "我保證乖乖(大概)"],
  },
  {
    id: 54,
    years: "8m",
    name: "碗粿",
    sex: "弟弟",
    old: "0~1歲",
    color: "黑",
    png: "./images/jodicat3.jpg",
    hashtag: ["話多", "黏人", "撒嬌"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我想吃肉泥", "奴才去哪?", "帶我回家好不好?"],
  },
  {
    id: 55,
    years: "10m",
    name: "肉圓",
    sex: "妹妹",
    old: "0~1歲",
    color: "橘",
    png: "./images/jodicat4.jpg",
    hashtag: ["慢熱", "話多", "黏人"],
    CatFriendly: false,
    needExperienced: true,
    quotes: ["我在冥想，勿擾", "鍵盤很好躺，我幫你上班", "你看起來就很好躺"],
  },
  {
    id: 56,
    years: "4m",
    name: "雪花",
    sex: "妹妹",
    old: "0~1歲",
    color: "白",
    png: "./images/phonecat1.jpg",
    hashtag: ["撒嬌", "話多"],
    CatFriendly: false,
    needExperienced: false,
    quotes: ["我想吃肉泥", "你去哪我就去哪", "逗貓棒一揮，我就是獵人"],
  },
];

async function seed() {
  console.log(`準備寫入 ${moreCats.length} 筆貓咪測試資料到 Firestore "cats" collection...`);

  for (const cat of moreCats) {
    const { id, ...data } = cat; // doc id 用 id，資料本身不重複存 id 欄位
    const ref = doc(db, "cats", String(id));
    await setDoc(ref, data);
    console.log(`已寫入: ${id} - ${cat.name}`);
  }

  console.log("全部完成！");
  process.exit(0);
}

seed().catch((err) => {
  console.error("寫入失敗：", err);
  console.error(
    "\n若錯誤是 permission-denied，請到 Firebase Console -> Firestore Database -> 規則，" +
      "暫時將 cats collection 開放寫入（例如 allow read, write: if true;），存完資料後記得改回安全的規則。"
  );
  process.exit(1);
});
